version: '2.1'
services:
  mariadb103:
    hostname: mariadb103.magento2.docker
    image: 'mariadb:10.3'
    env_file:
      - db.env
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - mariadb103.magento2.docker
  mariadb104nc:
    hostname: mariadb104nc.magento2.docker
    image: 'mariadb:10.4'
    env_file:
      - db.env
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - mariadb104nc.magento2.docker
    command: '--query_cache_size=0 --query_cache_type=0'
  mariadb104:
    hostname: mariadb104.magento2.docker
    image: 'mariadb:10.4'
    env_file:
      - db.env
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - mariadb104.magento2.docker
  mysql5:
    hostname: mysql5.magento2.docker
    image: 'mysql:5.6'
    env_file:
      - db.env
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - mysql5.magento2.docker
    command: '--default_authentication_plugin=mysql_native_password'
  mysql8:
    hostname: mysql8.magento2.docker
    image: 'mysql:8.0'
    env_file:
      - db.env
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - mysql8.magento2.docker
    command: '--default_authentication_plugin=mysql_native_password'
  app:
    hostname: app.magento2.docker
    build:
      context: '.'
    volumes:
      - './app:/app'
    networks:
      magento:
        aliases:
          - app.magento2.docker

networks:
  magento:
    driver: bridge
